# UNIX Makefile

PROJ_DIR = /home/docooler/workspace/c_plus_plus/name_define

#var makefile
include config.Makefile

#module makefile
include $(PROJ_DIR)/sw/swModule.Makefile

#target makefile
include targets.Makefile          


